version: '3'

services:
  spring-app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
      SPRING_DATASOURCE_USERNAME: rm553121
      SPRING_DATASOURCE_PASSWORD: 110205
    depends_on:
      - oracle-db

  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PASSWORD=YourSecurePassword
    ports:
      - 1521:1521
      - 5500:5500

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app
